id: I6880D221
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:34:53+00:00'
last_modified: '2022-06-08T14:35:07.247050+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00JR585
  title: ཉང་སྐྱེས་སྣང་མཛད་རྡོ་རྗེའི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2554':
      image_group_id: I00KG03998
      title: ''
      total_pages: 320
      order: 1
      base_file: 2554.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
